name: plots # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.8.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple graph plotting # 79 char long summary
description: |
  Plots makes it easy to visualise mathematical formulae.
  In addition to basic arithmetic operations, it supports 
  trigonometric, hyperbolic, exponential and logarithmic 
  functions, as well as arbitrary sums and products. It 
  can display polar equations, and both implicit and explicit Cartesian equations.
  Plots is designed to integrate well with the GNOME desktop and takes advantage of modern hardware using OpenGL.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo
license: GPL-3.0+
environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages
parts:
  plots:
    # See 'snapcraft plugins'
    plugin: python
    source: .
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    stage:
      # WORKAROUND: Skip venv from python plugin
      - -bin/activate
      - -bin/activate.csh
      - -bin/activate.fish
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -bin/pip
      - -bin/pip3
      - -pyvenv.cfg
    python-packages:
      - PyOpenGL
      - numpy
      - lark
      - PyGLM
      - freetype-py
    build-packages:
      - python3-jinja2
    override-stage: |
      craftctl default
      install -D -t $SNAPCRAFT_PRIME/usr/share/help/C/plots/ $SNAPCRAFT_PART_SRC/help/C/*
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - plots
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gnome-42-2204
      - gnome-42-2204-sdk
    override-prime: |
      set -eux
      for snap in "<CORE-SNAP>" "<CONTENT-SNAP-1>" "<CONTENT-SNAP-2>"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
apps:
  plots:
    command: bin/plots
    extensions: [gnome]
    common-id: com.github.alexhuntley.Plots
    desktop: snap/gui/plots.desktop
    plugs:
      - home
